### ISSUE TITLE
Link not working 

### ISSUE THREAD

**Issue by Iamtripathisatyam** [pamoroso/free-python-books#14]
- List of free python books
    - Free Programming Books: Python 
This section isn't functional and is returning 404 messages.

**Comment by pamoroso** [comment]
I'm not sure which section of [Free Python Books](https://github.com/pamoroso/free-python-books) you mean. Can you please provide some more context?

**Comment by Iamtripathisatyam** [comment]
https://github.com/pamoroso/free-python-books#lists-of-free-python-books

**Comment by pamoroso** [comment]
Got it, thanks. I've removed that link as the URL is now stale and the original resource is likely no longer available.

**Comment by Iamtripathisatyam** [comment]
Sir, Greetings! I'd want to contribute, but I'm not sure how to get started.

**Comment by pamoroso** [comment]
You already contributed by reporting a broken link. Thanks!

**Comment by Iamtripathisatyam** [comment]
Ya sir, I want to contribute on major projects
