### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ncwalk** [pamoroso/free-python-books#7]
I am rather new to Github - a 46 year old student just starting an AI Masters at Johns Hopkins, and I'm embarassed to say I can't figure out why I can't get the 'actual' books on my hard drive.  I forked your repository - which is amazing!!! - but when I download a zip, or clone it, I just get the logo, readme, no books.  Advice?

Thanks for your patience,
Nathan
nathan.walk@va.gov
nwalk3@jhu.edu

**Comment by fscheu** [comment]
Hello Nathan!
The books aren't in the repository. You have to use the links provided in the [readme](https://github.com/pamoroso/free-python-books#readme)

**Comment by ncwalk** [comment]
Ahhh.  Thank you.  I appreciate your patience!
Is there any way to tell that I missed?  I feel rather foolish😊
Nathan

**Comment by fscheu** [comment]
Jaja, As you, I'm also a 41 years old student rather new to github! keep learning!

**Comment by pamoroso** [comment]
Hello @ncwalk As @fscheu noted (thanks!) the actual text of the ebooks is not in the GitHub repository of the Free Python Books project.

The project's [README file](https://github.com/pamoroso/free-python-books#readme) includes only links to the official websites where the ebooks themselves are available. Each of the websites provides links or instructions for reading the books online or, in some cases, downloading the ebook files in ePub, Kindle, or PDF formats.
